console.log('🧪 Test: Verificar configuración de URL...');
console.log('');
console.log('📋 INSTRUCCIONES:');
console.log('1. Abre la consola del navegador (F12 -> Console)');
console.log('2. Ejecuta este código:');
console.log('');
console.log('// Verificar configuración actual');
console.log('import { getApiBaseUrl } from "./src/config.js";');
console.log('console.log("URL base detectada:", getApiBaseUrl());');
console.log('');
console.log('// O directamente:');
console.log('console.log("Hostname actual:", window.location.hostname);');
console.log('console.log("URL completa:", window.location.href);');
console.log('');
console.log('🔧 CAMBIO REALIZADO:');
console.log('✅ Modificado config.js para usar 192.168.203.24:3001 cuando se accede desde localhost');
console.log('');
console.log('🔄 SIGUIENTE PASO:');
console.log('1. Refresca la página del frontend (Ctrl+F5)');
console.log('2. Intenta imprimir un recibo nuevamente');
console.log('3. Verifica en la consola que ahora use la URL correcta');
console.log('');
console.log('❓ Si el problema persiste:');
console.log('- Verifica que el backend esté corriendo en 192.168.203.24:3001');
console.log('- Prueba acceder directamente a: http://192.168.203.24:3001/uploads/2cbdf63d071c0d69c656fa8bdb92e5d2.png');