version: '3.8'

services:
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: rrhh-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=34.176.164.98
      - DB_USER=root
      - DB_PASSWORD=pos38ric0S
      - DB_NAME=RRHH
      - DB_PORT=3306
      - JWT_SECRET=claveultrasecreta123
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    networks:
      - rrhh-network
    restart: unless-stopped
    command: npm run dev

  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rrhh-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rrhh-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  uploads_data:
    driver: local

networks:
  rrhh-network:
    driver: bridge