version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: rrhh-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=34.176.164.98
      - DB_USER=root
      - DB_PASSWORD=pos38ric0S
      - DB_NAME=RRHH
      - DB_PORT=3306
      - JWT_SECRET=claveultrasecreta123
      - "CORS_ORIGIN=https://rrhh.dbconsulting.com.ar,http://192.168.203.24:3000"
      - HOST=0.0.0.0
    volumes:
      - uploads_data:/app/uploads
    networks:
      - rrhh-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rrhh-frontend
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - backend
    networks:
      - rrhh-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  caddy_logs:
    driver: local

networks:
  rrhh-network:
    driver: bridge