version: '3.8'

services:
  backend:
    image: elcheloide/sistema-rrhh-backend:prueba
    container_name: rrhh-backend
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-RRHH}
      - DB_PORT=${DB_PORT:-3306}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - rrhh-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: elcheloide/sistema-rrhh-frontend:prueba
    container_name: rrhh-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    # No Caddy volumes needed for direct static serving
    networks:
      - rrhh-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3



networks:
  rrhh-network:
    driver: bridge
